# Generated by Django 4.0.4 on 2022-04-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='images',
            name='status',
        ),
    ]
