# Generated by Django 4.0.4 on 2022-04-16 11:52

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_title_images_name_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
        migrations.AddField(
            model_name='images',
            name='file_dicom',
            field=models.FileField(default='images/default.dcm', upload_to=images.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
