# Generated by Django 4.0.4 on 2022-04-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_images_category_images_file_dicom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
    ]
